-- Create why_choose_us table for the landing page value props section.

CREATE TABLE IF NOT EXISTS public.why_choose_us (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon_name TEXT NOT NULL,
  "order" INTEGER NOT NULL
);

ALTER TABLE public.why_choose_us ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'why_choose_us'
      AND policyname = 'Anyone can view why_choose_us rows'
  ) THEN
    CREATE POLICY "Anyone can view why_choose_us rows"
      ON public.why_choose_us FOR SELECT
      USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'why_choose_us'
      AND policyname = 'Admins can manage why_choose_us'
  ) THEN
    CREATE POLICY "Admins can manage why_choose_us"
      ON public.why_choose_us FOR ALL
      TO authenticated
      USING (public.has_role(auth.uid(), 'admin'::app_role));
  END IF;
END $$;

INSERT INTO public.why_choose_us (title, description, icon_name, "order")
VALUES
  (
    'Lightning Fast',
    'Automation-first development lets us deliver full MVPs 3× faster than traditional teams.',
    'Zap',
    1
  ),
  (
    'AI-Powered',
    'From smart assistants to internal tools - we embed AI directly into your workflows.',
    'Bot',
    2
  ),
  (
    'Secure & Scalable',
    'Built on Supabase with row-level security, encrypted storage, and GDPR-ready infrastructure.',
    'Lock',
    3
  ),
  (
    'UX-Driven Design',
    'Clean, modern UI paired with intuitive UX, designed around real user journeys.',
    'Palette',
    4
  );
